
/*
 * All REST responses from Flickr are handled by this function
 */
function jsonFlickrApi(rsp) { //Function adapted from example online
	
    if (rsp.stat != "ok"){
    // If this executes, something broke!
    	return;
    }
    
    //variable "s" is going to contain 
    //all the markup that is generated by the loop below
    var s = "";

    //this loop runs through every item and creates HTML that will display nicely on your page
    for (var i=0; i < rsp.photos.photo.length; i++) {
	    photo = rsp.photos.photo[i];
	
	    //notice that "s.jpg" is where you change the size of the image
	    t_url = 'http://farm'+ photo.farm +'.static.flickr.com/'+ photo.server +'/'+ 
	    photo.id +'_'+ photo.secret +'_s.jpg';
	
	    p_url = 'http://www.flickr.com/photos/'+ photo.owner +'/'+ photo.id;
	
	    s += '<li><a href="'+ p_url +'" title="'+ photo.title +'"><img alt="'+ photo.title +'" src="'+ t_url +'" /></a></li>';
    }

    //this tells the JavaScript to write everything in variable s onto the page
    document.writeln("<ul>"+s+"</ul>");
 
}


function ParseXMLResponse(responseXML)
{
	 var hash = (responseXML.getElementsByTagName("hash")[0]).childNodes[0].nodeValue;
	 
	 var responseText = "<h2>AJAX XML response from server: " + hash + "</h2>";

	 return responseText;
}

function getFrobHash(func){ 
	//var apikey = "301748fd9ccc9801f9ed91772b19d8bd";
	//var secret = "a6d78a61a59fbf33";
	//var userid = "55164508@N02";
	
	//var out = "a6d78a61a59fbf33" + "api_key" + "301748fd9ccc9801f9ed91772b19d8bd" + "formatjson" + "methodflickr.auth.getFrob" + "userid" + userid;
	//var hash = hex_md5(out);

		
	if (window.XMLHttpRequest)
	  {// code for IE7+, Firefox, Chrome, Opera, Safari
	  xmlhttp=new XMLHttpRequest();
	  }
	else
	  {// code for IE6, IE5
	  xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	  }
	  
	xmlhttp.onreadystatechange=function()
	  {
	  if (xmlhttp.readyState==4 && xmlhttp.status==200)
	    {
		    //parse XML response from server
		    var responseText= ParseXMLResponse(xmlhttp.responseXML);
		    //alert("responseText: " + responseText);   
			
	    	document.getElementById("responseDiv").innerHTML=responseText;
	    	//load hash value into hidden variable
	    	
	    	document.getElementById("hash").value = (xmlhttp.responseXML.getElementsByTagName("hash")[0]).childNodes[0].nodeValue;
	    	alert("Inside js: " + document.getElementById("hash").value );
	    }
	  };
	
	//var func = "getFrob";
	var Params = "func=" + func;
	
	xmlhttp.open("POST","/CraigsBayAuctionHouse/flickrServlet" ,true); 
	xmlhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
	xmlhttp.send(Params);

}




function flickrUpload(){
	
	
	
}





