
function jsonFlickrApi(rsp) {
	
    if (rsp.stat != "ok"){
    // If this executes, something broke!
    	return;
    }
    //variable "s" is going to contain 
    //all the markup that is generated by the loop below
    var s = "";

    //this loop runs through every item and creates HTML that will display nicely on your page
    for (var i=0; i < rsp.photos.photo.length; i++) {
	    photo = rsp.photos.photo[i];
	
	    //notice that "s.jpg" is where you change the size of the image
	    t_url = 'http://farm'+ photo.farm +'.static.flickr.com/'+ photo.server +'/'+ 
	    photo.id +'_'+ photo.secret +'_s.jpg';
	
	    p_url = 'http://www.flickr.com/photos/'+ photo.owner +'/'+ photo.id;
	
	    s += '<li><a href="'+ p_url +'" title="'+ photo.title +'"><img alt="'+ photo.title +'" src="'+ t_url +'" /></a></li>';
    }

    //this tells the JavaScript to write everything in variable s onto the page
    document.writeln("<ul>"+s+"</ul>");
 
}

function getSig(){
	var apikey = "301748fd9ccc9801f9ed91772b19d8bd";
	var secret = "a6d78a61a59fbf33";
	var userid = "55164508@N02";
	var token;
	
	//a6d78a61a59fbf33api_key301748fd9ccc9801f9ed91772b19d8bdformatjsonuserid55164508@N02
	
	//This hash function might not work with Flickr
	var hash = hex_md5("a6d78a61a59fbf33" + "api_key" + "301748fd9ccc9801f9ed91772b19d8bd" + "formatjson" + "userid" + "55164508@N02" );

	//var hash = hex_md5(secret + "api_key" + apikey + "formatjson" + "userid" + userid );
	
	//var hash = MD5(secret + "api_key" + apikey  + "auth_token" + token + "submitUpload"); 
	
	
	document.getElementById("hash").value = hash;
	//alert(document.getElementById("hash").value );


}

function getFrob(){
	
	
	
}




function flickrUpload(){
	
	
}